name: Deploy to DigitalOcean Droplet
on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder workflow for DigitalOcean deployment."
